#pragma once

#define CHUNK_EDGE_LENGTH 16
#define CHUNK_VOXEL_COUNT CHUNK_EDGE_LENGTH * CHUNK_EDGE_LENGTH * CHUNK_EDGE_LENGTH
#define CHUNK_MAX_LOADED_COUNT 1000
#define CHUNK_MAX_VOXEL_VALUE_F 254.0f
#define CHUNK_MAX_VERTICES_PER_CHUNK 5 * (CHUNK_EDGE_LENGTH - 1) * (CHUNK_EDGE_LENGTH - 1) * (CHUNK_EDGE_LENGTH - 1)
#define CHUNK_MAX_VOXEL_VALUE_I 254
#define CHUNK_SPECIAL_VALUE 255
#define CHUNK_SURFACE_LEVEL 70

#define PLAYER_MAX_COUNT 50
#define PLAYER_SHAPE_SWITCH_DURATION 0.3f
#define PLAYER_MAX_ACTIONS_COUNT 100
#define PLAYER_SCALE vector3_t(0.5f)
#define PLAYER_TERRAFORMING_SPEED 200.0f
#define PLAYER_TERRAFORMING_RADIUS 3.0f
