#pragma once

#define NET_MAX_CLIENT_COUNT 50
#define NET_MAX_ACCUMULATED_PREDICTED_CHUNK_MODIFICATIONS_PACK_COUNT 60
#define NET_MAX_ACCUMULATED_PREDICTED_CHUNK_MODIFICATIONS_PER_PACK MAX_PREDICTED_CHUNK_MODIFICATIONS * 5
#define NET_MAX_MESSAGE_SIZE 65507
#define NET_MAX_AVAILABLE_SERVER_COUNT 1000
#define NET_CLIENT_COMMAND_OUTPUT_INTERVAL (1.0f / 25.0f)
#define NET_SERVER_SNAPSHOT_OUTPUT_INTERVAL (1.0f / 20.0f)
#define NET_SERVER_CHUNK_WORLD_OUTPUT_INTERVAL (1.0f / 40.0f)
#define NET_PING_INTERVAL 2.0f
#define NET_CLIENT_TIMEOUT 5.0f
